### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by sky-whs** [raymondyeh07/tv_layers_for_cv#1]
Thank you for your awesome works!
I follow your tutorial, but when I run python setup.py install, this problem as title has shown. And my gcc version is 9.4.0.
Can you check out some dependency of your code?

**Comment by raymondyeh07** [comment]
I am using:
- Ubuntu 20.04.2 LTS
- Python 3.7.11
- GCC 9.3.0
- torch 1.9.0
- torchvision 0.2.2
- CUDA 11.1
- Nvidia Driver 455.23.05
