### ISSUE TITLE
TV with learneable D

### ISSUE THREAD

**Issue by swami1995** [raymondyeh07/tv_layers_for_cv#3]
Thanks for the amazing work!

I was wondering if you guys have also tried to write an implementation where D can be fed into the TV layer as a parameter and get gradients for the corresponding D matrix? (Specifically D could be parameterized using a 1xN vector or 2xNxC (N=kernel length (say 2 or 3), C=number of channels) which is what would be fed in and used for gradient computation.

And if I had to try to implement that on top of your current implementation, could you point me towards how I could go about it? Thanks!

**Comment by raymondyeh07** [comment]
Hi @swami1995,

We have not tried learning the difference matrix D. The TV solver takes advantage of the specific structure of D for speedup.
It would no longer be a TV problem if D is being learned, hence, one would have to utilized a different solver.

Best,
Raymond
