### ISSUE TITLE
compared with tv loss

### ISSUE THREAD

**Issue by coffe33machine** [raymondyeh07/tv_layers_for_cv#4]
hi, can you explain the difference between your method and simply adding a TV loss? Thank you.

**Comment by raymondyeh07** [comment]
Hi @coffe33machine , 

The paper introduces a TV-Optimization "layer." This layer's "forward pass" solves the optimization problem specified in Eq. 1. Think of it as an additional building block to the architecture. In other words, the method is orthogonal to adding a loss. A TV loss can be applied in conjunction with our method.

Best,
Raymond
