### ISSUE TITLE
Unable to compile tv_opt module.

### ISSUE THREAD

**Issue by lsjBatter** [raymondyeh07/tv_layers_for_cv#5]
There are the following problems when installing according to the method you provided.
![image](https://github.com/raymondyeh07/tv_layers_for_cv/assets/99625994/50c6d0c8-cf04-4ac0-bfb3-5dbd6f9dd433)
The above situation still occurs when the calculation force is set to 8.0 or 7.5.
The following error occurred after changing ['ninja', '-v'] to ['Ninja','-version'].
![image](https://github.com/raymondyeh07/tv_layers_for_cv/assets/99625994/af0061c5-d136-4a74-8af7-681cf02d5745)
Could you please share the complete file directory after compilation?
GPU：RTX3090
Linux：Ubuntu18.04

**Comment by raymondyeh07** [comment]
Hi @lsjBatter,

I think your nvcc version might be too old.

Best,
Raymond
